var allemand = {};
allemand["lang"] = "de";
allemand["element_1"] = " / Diebstahlanzeige"; //ANCIENNE TRAD
allemand["element_2"] = " / Art des Diebstahls";
allemand["element_3"] = " / Taschendiebstahl (das Opfer trug die gestohlenen Gegenstände bei sich, in den Kleidertaschen oder in einer Handtasche)";
allemand["element_4"] = " / einfacher Diebstahl (Gegenstände auf dem Boden oder auf einem Tisch liegend.)";
allemand["element_5"] = " / Erklären Sie, wo sich der entwendete Gegenstand oder die entwendeten Gegenstände befanden)";
allemand["element_6"] = " / Datum des Vorfalls";
allemand["element_7"] = " / Zeit Fakten";
allemand["element_8"] = " / Tatort"; //ANCIENNE TRAD
allemand["element_9"] = " / Geschädigte";
allemand["element_10"] = " / Name"; // TRADUCTION EN ATTENTE
allemand["element_11"] = " / Vorname";
allemand["element_12"] = " / Geburtsdatum";
allemand["element_13"] = " / Geburtsort";
allemand["element_14"] = " / Staatsangehörigkeit";
allemand["element_15"] = " / Beruf";
allemand["element_16"] = " / Details des Opfers";
allemand["element_17"] = " / Adresse";
allemand["element_18"] = " / Telefonnummer";
allemand["element_19"] = " / E-Mail";
allemand["element_20"] = " / Anschrift in Paris";
allemand["element_21"] = " / Dauer des Aufenthalts"; //ANCIENNE TRAD
allemand["element_22"] = " / Beschreibung des (der) Täters (er)";
allemand["element_22_bis"] = " / Beschreibung des (der) Täters (er)";
allemand["element_23"] = " / (Ich bin nicht in der Lage, den oder die Täter dieses Diebstahls wieder zu erkennen. Trotz allem kann ich folgende Angaben machen)"; // TRADUCTION EN ATTENTE
allemand["element_24"] = " / Personenanzahl";
allemand["element_25"] = " / Geschlecht";
allemand["element_26"] = " / männlich";
allemand["element_27"] = " / weiblich";
allemand["element_28"] = " / Alter";
allemand["element_29"] = " / Größe (cms)";
allemand["element_30"] = " / Korpulenz";
allemand["element_31"] = " / dick";
allemand["element_32"] = " / normal";
allemand["element_33"] = " / dünn";
allemand["element_34"] = " / Typ"; // VERIFIER TRADUCTION
allemand["element_40"] = " / andere";
allemand["element_41"] = " / Haarfarbe";
allemand["element_42"] = " / schwarz";
allemand["element_43"] = " / braun";
allemand["element_44"] = " / blond";
allemand["element_45"] = " / weiß";
allemand["element_46"] = " / rötlich";
allemand["element_47"] = " / Glatze";
allemand["element_49"] = " / besondere Merkmale";
allemand["element_50"] = " / Schnurrbart";
allemand["element_51"] = " / Bart";
allemand["element_52"] = " / Brille";
allemand["element_53"] = " / Narbe";
allemand["element_54"] = " / Tätowierung";
allemand["element_55"] = " / Piercing";
// Duplication
allemand["element_25_bis"] = " / Geschlecht";
allemand["element_26_bis"] = " / männlich";
allemand["element_27_bis"] = " / weiblich";
allemand["element_28_bis"] = " / Alter";
allemand["element_29_bis"] = " / Größe (cms)";
allemand["element_30_bis"] = " / Korpulenz";
allemand["element_31_bis"] = " / dick";
allemand["element_32_bis"] = " / normal";
allemand["element_33_bis"] = " / dünn";
allemand["element_34_bis"] = " / Typ"; // VERIFIER TRADUCTION
allemand["element_40_bis"] = " / andere";
allemand["element_41_bis"] = " / Haarfarbe";
allemand["element_42_bis"] = " / schwarz";
allemand["element_43_bis"] = " / braun";
allemand["element_44_bis"] = " / blond";
allemand["element_45_bis"] = " / weiß";
allemand["element_46_bis"] = " / rötlich";
allemand["element_47_bis"] = " / Glatze";
allemand["element_49_bis"] = " / besondere Merkmale";
allemand["element_50_bis"] = " / Schnurrbart";
allemand["element_51_bis"] = " / Bart";
allemand["element_52_bis"] = " / Brille";
allemand["element_53_bis"] = " / Narbe";
allemand["element_54_bis"] = " / Tätowierung";
allemand["element_55_bis"] = " / Piercing";
// Fin Duplication
allemand["element_56"] = " / eingetretener Schaden";
allemand["element_57"] = " / entwendete Gegenstände";
allemand["element_58"] = " / Geben Sie wenn möglich die Seriennummer oder die IMEI Nummer an";
allemand["element_59"] = " / Handtasche, Brieftasche oder Geldbeutel";
allemand["element_60"] = " / Bargeld";
allemand["element_61"] = " / Kreditkarte";
allemand["element_62"] = " / Reiseschecks";
allemand["element_63"] = " / Flugschein";
allemand["element_64"] = " / Reisepass";
allemand["element_65"] = " / Personalausweis";
allemand["element_66"] = " / Führerschein";
allemand["element_67"] = " / Handy";
allemand["element_68"] = " / Fotoapparat";
allemand["element_69"] = " / Camcorder";
allemand["element_70"] = " / Schmuck";
allemand["element_71"] = " / Andere Gegenstände";
allemand["element_72"] = " / hinzufügen";
allemand["element_73"] = " / Tathergang";
allemand["element_74"] = " / Sachverhaltsschilderung";
allemand["element_75"] = " / Unterschrift des Anzeigeerstatters";
allemand["element_76"] = " / Hiermit erstatte ich Anzeige gegen unbekannt wegen Diebstahls bei der Staatsanwaltschaft beim Oberlandgericht von Paris";
allemand["element_77"] = " / früher";
allemand["element_78"] = " / folgende";
allemand["element_79"] = "";
allemand["element_80"] = " / entfernen";
allemand["element_81"] = " / rücksetzen";
allemand["element_82"] = " / Täter 1";
allemand["element_83"] = " / Täter 2";
allemand["element_84"] = "";
allemand["element_85"] = "";
allemand["element_86"] = "";
allemand["element_87"] = "";
allemand["element_88"] = "";
allemand["element_89"] = "";
allemand["element_90"] = "";
allemand["element_91"] = "";
allemand["element_92"] = ""; // TRADUCTION MANQUANTE
allemand["element_93"] = ""; // TRADUCTION MANQUANTE
allemand["element_94"] = ""; // TRADUCTION MANQUANTE
allemand["element_95"] = ""; // TRADUCTION MANQUANTE
allemand["element_96"] = ""; // TRADUCTION EN ATTENTE
allemand["element_97"] = ""; // TRADUCTION EN ATTENTE
allemand["element_98"] = ""; // TRADUCTION EN ATTENTE
allemand["element_99"] = ""; // TRADUCTION EN ATTENTE
allemand["element_100"] = ""; // TRADUCTION EN ATTENTE
allemand["element_101"] = ""; // TRADUCTION EN ATTENTE
