var arabe = {};
arabe["lang"] = "ar";
arabe["element_1"] = "رســـــالة شكــــــوى لــــسرقـــــة / "; //ANCIENNE TRAD
arabe["element_2"] = "نوع السرقة / ";
arabe["element_3"] = "(ن شل (سرقة اشياء محمولة من طرف الضحية ،في جيبه أو في حقيبته / ";
arabe["element_4"] = "<br> سرقة بسيطة ( سرقة اشياء مطروحة على الرض أو على طاولة أومن وراء الظهر) / ";
arabe["element_5"] = "وضح أين كانت الشياء المسروقة / ";
arabe["element_6"] = "اريخ الحدث و الساعة / ";
arabe["element_7"] = "حقائق مرة / ";
arabe["element_8"] = "مكان الحدث / "; //ANCIENNE TRAD
arabe["element_9"] = "الضـــحــــيـــــة / ";
arabe["element_10"] = "(اللقب(إسم العائلة / "; // TRADUCTION EN ATTENTE
arabe["element_11"] = "لسم الشخصي / ";
arabe["element_12"] = "تاريخ الميلد / ";
arabe["element_13"] = "مكان الميلد / ";
arabe["element_14"] = "الجنسية / ";
arabe["element_15"] = "المهنة / ";
arabe["element_16"] = "تفاصيل عن الضحية / ";
arabe["element_17"] = "العنوان / ";
arabe["element_18"] = "رقم الهاتف / ";
arabe["element_19"] = "ع . إ لكتروني / ";
arabe["element_20"] = "العنوان في باريس / ";
arabe["element_21"] = "مدة البقاء / "; //ANCIENNE TRAD
arabe["element_22"] = "وصف مرتكب السرقةا أو السراق / ";
arabe["element_22_bis"] = "وصف مرتكب السرقةا أو السراق / ";
arabe["element_23"] = "نا لست قادراعلى العتراف بالسارق لكن يمكن لي أن أوضح العناصرالتالية / "; // TRADUCTION EN ATTENTE
arabe["element_24"] = "عدد الشخاص / ";
arabe["element_25"] = " الجنس : / ";
arabe["element_26"] = "رجل / ";
arabe["element_27"] = "إمراة / ";
arabe["element_28"] = "العمر / ";
arabe["element_29"] = "(القامة ( سم / ";
arabe["element_30"] = "سمنة / ";
arabe["element_31"] = "جسيم / ";
arabe["element_32"] = "متوسط / ";
arabe["element_33"] = "نحيف / ";
arabe["element_34"] = "الشخص / "; // VERIFIER TRADUCTION
arabe["element_40"] = "آخر / ";
arabe["element_41"] = "لون الشعر / ";
arabe["element_42"] = "أسود / ";
arabe["element_43"] = "أسمر / ";
arabe["element_44"] = "أشقر / ";
arabe["element_45"] = "أبيض / ";
arabe["element_46"] = "أصهب / ";
arabe["element_47"] = "أصلع / ";
arabe["element_49"] = "خاصيات : / ";
arabe["element_50"] = "شارب / ";
arabe["element_51"] = "لحية / ";
arabe["element_52"] = "نضارات / ";
arabe["element_53"] = "ندبة / ";
arabe["element_54"] = "وشم / ";
arabe["element_55"] = "مثقوب الجسم برسين / ";
// Duplication
arabe["element_25_bis"] = " الجنس : / ";
arabe["element_26_bis"] = "رجل / ";
arabe["element_27_bis"] = "إمراة / ";
arabe["element_28_bis"] = "العمر / ";
arabe["element_29_bis"] = "(القامة ( سم / ";
arabe["element_30_bis"] = "سمنة / ";
arabe["element_31_bis"] = "جسيم / ";
arabe["element_32_bis"] = "متوسط / ";
arabe["element_33_bis"] = "نحيف / ";
arabe["element_34_bis"] = "الشخص / "; // VERIFIER TRADUCTION
arabe["element_40_bis"] = "آخر / ";
arabe["element_41_bis"] = "لون الشعر / ";
arabe["element_42_bis"] = "أسود / ";
arabe["element_43_bis"] = "أسمر / ";
arabe["element_44_bis"] = "أشقر / ";
arabe["element_45_bis"] = "أبيض / ";
arabe["element_46_bis"] = "أصهب / ";
arabe["element_47_bis"] = "أصلع / ";
arabe["element_49_bis"] = "خاصيات : / ";
arabe["element_50_bis"] = "شارب / ";
arabe["element_51_bis"] = "لحية / ";
arabe["element_52_bis"] = "نضارات / ";
arabe["element_53_bis"] = "ندبة / ";
arabe["element_54_bis"] = "وشم / ";
arabe["element_55_bis"] = "مثقوب الجسم برسين / ";
// Fin Duplication
arabe["element_56"] = "لخـــســارة / ";
arabe["element_57"] = "لشياء المسروقة / ";
arabe["element_58"] = "إشارة الرقم المتتابع / ";
arabe["element_59"] = "قيبة يد,كيس نقود / ";
arabe["element_60"] = "نقود / ";
arabe["element_61"] = "ببطاقة قرض / ";
arabe["element_62"] = "صكوك سفر / ";
arabe["element_63"] = "تذكرة طائرة / ";
arabe["element_64"] = "جواز السفر / ";
arabe["element_65"] = "بطاقة تعريف / ";
arabe["element_66"] = "رخصة السياقة / ";
arabe["element_67"] = "الهاتف المحمول / ";
arabe["element_68"] = "آلة التصوير / ";
arabe["element_69"] = "الكامسكوب / ";
arabe["element_70"] = "جوهرات / ";
arabe["element_71"] = "حاجات أخرى / ";
arabe["element_72"] = "إضافة / ";
arabe["element_73"] = "كيفية العملية / ";
arabe["element_74"] = "أوصف لنا، كما تظن ، الطريقة التي استعملها السارق / ";
arabe["element_75"] = "مضاء المشتكي / ";
arabe["element_76"] = "شرفني ان أقدم ضد شخص مجهول شكوى خاصة بالحداث المشار إليها آنفا امام وكيل الجمهورية لدىمحكمة باريس الجنائية / ";
arabe["element_77"] = " سابق / ";
arabe["element_78"] = "التالي / ";
arabe["element_79"] = "";
arabe["element_80"] = "نزع / ";
arabe["element_81"] = "أعاد التشغيل / ";
arabe["element_82"] = "الشخص  1 / ";
arabe["element_83"] = "أالشخص 2 / ";
arabe["element_84"] = "";
arabe["element_85"] = "";
arabe["element_86"] = "";
arabe["element_87"] = "";
arabe["element_88"] = "";
arabe["element_89"] = "";
arabe["element_90"] = "";
arabe["element_91"] = "";
arabe["element_92"] = ""; // TRADUCTION MANQUANTE
arabe["element_93"] = ""; // TRADUCTION MANQUANTE
arabe["element_94"] = ""; // TRADUCTION MANQUANTE
arabe["element_95"] = ""; // TRADUCTION MANQUANTE
arabe["element_96"] = ""; // TRADUCTION EN ATTENTE
arabe["element_97"] = ""; // TRADUCTION EN ATTENTE
arabe["element_98"] = ""; // TRADUCTION EN ATTENTE
arabe["element_99"] = ""; // TRADUCTION EN ATTENTE
arabe["element_100"] = ""; // TRADUCTION EN ATTENTE
arabe["element_101"] = ""; // TRADUCTION EN ATTENTE
