var coreen = {};
coreen["lang"] = "ko";
coreen["element_1"] = " / 도난신고서"; //ANCIENNE TRAD
coreen["element_2"] = " / 도난 형태";
coreen["element_3"] = " / 소매치기";
coreen["element_4"] = " / 단순 도난(바닥이나 테이블 위 또는 등 뒤에서 )";
coreen["element_5"] = " / 도난물건이 있었던 곳을 구체적으로 기입하세요";
coreen["element_6"] = " / 이벤트 날짜";
coreen["element_7"] = " / 이벤트 시간";
coreen["element_8"] = " / 사건 발생장소"; //ANCIENNE TRAD
coreen["element_9"] = " / 피해자";
coreen["element_10"] = " / 성"; // TRADUCTION EN ATTENTE
coreen["element_11"] = " / 이름";
coreen["element_12"] = " / 생년월일";
coreen["element_13"] = " / 출생지 ";
coreen["element_14"] = " / 국적";
coreen["element_15"] = " / 직업";
coreen["element_16"] = " / 피해자의 좌표";
coreen["element_17"] = " / 한국내 주소";
coreen["element_18"] = " / 전화번호";
coreen["element_19"] = " / 이메일";
coreen["element_20"] = " / 파리내 거주지 주소";
coreen["element_21"] = " / 파리 체제 기간"; //ANCIENNE TRAD
coreen["element_22"] = " / 범인 묘사";
coreen["element_22_bis"] = " / 범인 묘사";
coreen["element_23"] = " / 범인을 알아볼 수는 없지만 다음 내용을 기입할 수 있습니다"; // TRADUCTION EN ATTENTE
coreen["element_24"] = " / 범인 수";
coreen["element_25"] = " / 성별";
coreen["element_26"] = " / 남성";
coreen["element_27"] = " / 여성";
coreen["element_28"] = " / 나이";
coreen["element_29"] = " / 키 (cms)";
coreen["element_30"] = " / 비만";
coreen["element_31"] = " / 뚱뚱한편";
coreen["element_32"] = " / 보통";
coreen["element_33"] = " / 마른편";
coreen["element_34"] = " / 타입"; // VERIFIER TRADUCTION
coreen["element_40"] = " / 기타";
coreen["element_41"] = " / 머리카락색깔";
coreen["element_42"] = " / 검은색";
coreen["element_43"] = " / 갈색";
coreen["element_44"] = " / 금발";
coreen["element_45"] = " / 흰색";
coreen["element_46"] = " / 붉은색";
coreen["element_47"] = " / 대머리";
coreen["element_49"] = " / 특징";
coreen["element_50"] = " / 콧수염";
coreen["element_51"] = " / 턱수염";
coreen["element_52"] = " / 안경 ";
coreen["element_53"] = " / 상처자국";
coreen["element_54"] = " / 문신";
coreen["element_55"] = " / 피어싱";
// Duplication
coreen["element_25_bis"] = " / 성별";
coreen["element_26_bis"] = " / 남성";
coreen["element_27_bis"] = " / 여성";
coreen["element_28_bis"] = " / 나이";
coreen["element_29_bis"] = " / 키 (cms)";
coreen["element_30_bis"] = " / 비만";
coreen["element_31_bis"] = " / 뚱뚱한편";
coreen["element_32_bis"] = " / 보통";
coreen["element_33_bis"] = " / 마른편";
coreen["element_34_bis"] = " / 타입"; // VERIFIER TRADUCTION
coreen["element_40_bis"] = " / 기타";
coreen["element_41_bis"] = " / 머리카락색깔";
coreen["element_42_bis"] = " / 검은색";
coreen["element_43_bis"] = " / 갈색";
coreen["element_44_bis"] = " / 금발";
coreen["element_45_bis"] = " / 흰색";
coreen["element_46_bis"] = " / 붉은색";
coreen["element_47_bis"] = " / 대머리";
coreen["element_49_bis"] = " / 특징";
coreen["element_50_bis"] = " / 콧수염";
coreen["element_51_bis"] = " / 턱수염";
coreen["element_52_bis"] = " / 안경 ";
coreen["element_53_bis"] = " / 상처자국";
coreen["element_54_bis"] = " / 문신";
coreen["element_55_bis"] = " / 피어싱";
// Fin Duplication
coreen["element_56"] = " / 피해내용";
coreen["element_57"] = " / 도난물건";
coreen["element_58"] = " / 가능하면 IMEI 시리얼 넘버를 기입하세요";
coreen["element_59"] = " / 헨드백, 지갑 또는 동전지갑";
coreen["element_60"] = " / 현금";
coreen["element_61"] = " / 은행카드";
coreen["element_62"] = " / 여행자 수표";
coreen["element_63"] = " / 항공권";
coreen["element_64"] = " / 여권";
coreen["element_65"] = " / 신분증";
coreen["element_66"] = " / 운전면허증";
coreen["element_67"] = " / 휴대폰";
coreen["element_68"] = " / 카메라";
coreen["element_69"] = " / 캠코더";
coreen["element_70"] = " / 보석";
coreen["element_71"] = " / 기타";
coreen["element_72"] = " / 추가";
coreen["element_73"] = " / 상황 설명";
coreen["element_74"] = " / 도난발생 상황을 설명하세요";
coreen["element_75"] = " / 본인서명 ";
coreen["element_76"] = " / 본인은 파리 지방법원 검사장에게 앞에서 인용한 사실에 대해 불특정 범인을 상대로 고소장을접수시키는 바입니다.";
coreen["element_77"] = " / 이전";
coreen["element_78"] = " / 다음의";
coreen["element_79"] = "";
coreen["element_80"] = " / 제거";
coreen["element_81"] = " / 재설정";
coreen["element_82"] = " / 범인 1";
coreen["element_83"] = " / 범인 2";
coreen["element_84"] = "";
coreen["element_85"] = "";
coreen["element_86"] = "";
coreen["element_87"] = "";
coreen["element_88"] = "";
coreen["element_89"] = "";
coreen["element_90"] = "";
coreen["element_91"] = "";
coreen["element_92"] = ""; // TRADUCTION MANQUANTE
coreen["element_93"] = ""; // TRADUCTION MANQUANTE
coreen["element_94"] = ""; // TRADUCTION MANQUANTE
coreen["element_95"] = ""; // TRADUCTION MANQUANTE
coreen["element_96"] = ""; // TRADUCTION EN ATTENTE
coreen["element_97"] = ""; // TRADUCTION EN ATTENTE
coreen["element_98"] = ""; // TRADUCTION EN ATTENTE
coreen["element_99"] = ""; // TRADUCTION EN ATTENTE
coreen["element_100"] = ""; // TRADUCTION EN ATTENTE
coreen["element_101"] = ""; // TRADUCTION EN ATTENTE
