var espagnol = {};
espagnol["lang"] = "es";
espagnol["element_1"] = " / Denuncia de robo"; //ANCIENNE TRAD
espagnol["element_2"] = " / Tipo de robo";
espagnol["element_3"] = " / tirón (sustracción del bolso que llevaba la víctima) o robo con violencia de objetos en los bolsillos";
espagnol["element_4"] = " / hurto (robo de objetos dejados en el suelo o sobre una mesa, o en los bolsillos)";
espagnol["element_5"] = " / Indique donde se hallaban el o los objetos sustraídos";
espagnol["element_6"] = " / Fecha de lo ocurrido";
espagnol["element_7"] = " / Hora de lo ocurrido";
espagnol["element_8"] = " / Lugar"; //ANCIENNE TRAD
espagnol["element_9"] = " / La identidad de la víctima";
espagnol["element_10"] = " / Apellidos"; // TRADUCTION EN ATTENTE
espagnol["element_11"] = " / Nombre";
espagnol["element_12"] = " / Fecha de nacimiento";
espagnol["element_13"] = " / Lugar de nacimiento";
espagnol["element_14"] = " / Nacionalidad";
espagnol["element_15"] = " / Oficio";
espagnol["element_16"] = " / Los detalles de la víctima";
espagnol["element_17"] = " / Dirección";
espagnol["element_18"] = " / Número de teléfono";
espagnol["element_19"] = " / dirección electrónica";
espagnol["element_20"] = " / Dirección en Paris";
espagnol["element_21"] = " / Duración de estancia"; //ANCIENNE TRAD
espagnol["element_22"] = " / Descripcíon del (de los) autor(es)";
espagnol["element_22_bis"] = " / Descripcíon del (de los) autor(es)";
espagnol["element_23"] = " / No soy capaz de reconocer el (los) autor (es) del robo, sin embargo puedo añadir detalles que se refieren a su(s)"; // TRADUCTION EN ATTENTE
espagnol["element_24"] = " / Número de personas";
espagnol["element_25"] = " / Sexo";
espagnol["element_26"] = " / hombre";
espagnol["element_27"] = " / mujer";
espagnol["element_28"] = " / Edad";
espagnol["element_29"] = " / Talla (cms)";
espagnol["element_30"] = " / corpulencia";
espagnol["element_31"] = " / gordo";
espagnol["element_32"] = " / normal";
espagnol["element_33"] = " / delgado/flaco";
espagnol["element_34"] = " / Tipo"; // VERIFIER TRADUCTION
espagnol["element_40"] = " / otro";
espagnol["element_41"] = " / color de pelo";
espagnol["element_42"] = " / negro";
espagnol["element_43"] = " / moreno";
espagnol["element_44"] = " / rubio";
espagnol["element_45"] = " / cano";
espagnol["element_46"] = " / pelirrojo";
espagnol["element_47"] = " / calvo";
espagnol["element_49"] = " / señas particulares";
espagnol["element_50"] = " / bigote";
espagnol["element_51"] = " / barba";
espagnol["element_52"] = " / gafas";
espagnol["element_53"] = " / cicatriz";
espagnol["element_54"] = " / tatuaje";
espagnol["element_55"] = " / pirsin";
// Duplication
espagnol["element_25_bis"] = " / Sexo";
espagnol["element_26_bis"] = " / hombre";
espagnol["element_27_bis"] = " / mujer";
espagnol["element_28_bis"] = " / Edad";
espagnol["element_29_bis"] = " / Talla (cms)";
espagnol["element_30_bis"] = " / corpulencia";
espagnol["element_31_bis"] = " / gordo";
espagnol["element_32_bis"] = " / normal";
espagnol["element_33_bis"] = " / delgado/flaco";
espagnol["element_34_bis"] = " / Tipo"; // VERIFIER TRADUCTION
espagnol["element_40_bis"] = " / otro";
espagnol["element_41_bis"] = " / color de pelo";
espagnol["element_42_bis"] = " / negro";
espagnol["element_43_bis"] = " / moreno";
espagnol["element_44_bis"] = " / rubio";
espagnol["element_45_bis"] = " / cano";
espagnol["element_46_bis"] = " / pelirrojo";
espagnol["element_47_bis"] = " / calvo";
espagnol["element_49_bis"] = " / señas particulares";
espagnol["element_50_bis"] = " / bigote";
espagnol["element_51_bis"] = " / barba";
espagnol["element_52_bis"] = " / gafas";
espagnol["element_53_bis"] = " / cicatriz";
espagnol["element_54_bis"] = " / tatuaje";
espagnol["element_55_bis"] = " / pirsin";
// Fin Duplication
espagnol["element_56"] = " / Perjuicio";
espagnol["element_57"] = " / Objetos sustraídos";
espagnol["element_58"] = " / indique cualquier detalle útil (el número de serie o IMEI)";
espagnol["element_59"] = " / bolso de mano, cartera o monedero";
espagnol["element_60"] = " / dinero en efectivo";
espagnol["element_61"] = " / tarjeta de crédito";
espagnol["element_62"] = " / cheques de viaje";
espagnol["element_63"] = " / billete de avión";
espagnol["element_64"] = " / pasaporte";
espagnol["element_65"] = " / Documento Nacional de Identidad";
espagnol["element_66"] = " / Permiso de conducir";
espagnol["element_67"] = " / Móvil";
espagnol["element_68"] = " / Maquina de fotos";
espagnol["element_69"] = " / Videocámara";
espagnol["element_70"] = " / Joyas";
espagnol["element_71"] = " / Otro objeto";
espagnol["element_72"] = " / Añadir";
espagnol["element_73"] = " / modus operandi";
espagnol["element_74"] = " / Describa cómo, según usted, ocurrió el robo / hurto";
espagnol["element_75"] = " / Firma el denunciante";
espagnol["element_76"] = " / Tengo el honor de denunciar contra desconocidos los hechos relatados más arriba, ante el Señor Fiscal del Tribunal de Grande Instance de Paris";
espagnol["element_77"] = " / anterior";
espagnol["element_78"] = " / Próximo";
espagnol["element_79"] = "";
espagnol["element_80"] = " / eliminar";
espagnol["element_81"] = " / reajustar";
espagnol["element_82"] = " / Individuo 1";
espagnol["element_83"] = " / Individuo 2";
espagnol["element_84"] = "";
espagnol["element_85"] = "";
espagnol["element_86"] = "";
espagnol["element_87"] = "";
espagnol["element_88"] = "";
espagnol["element_89"] = "";
espagnol["element_90"] = "";
espagnol["element_91"] = "";
espagnol["element_92"] = ""; // TRADUCTION MANQUANTE
espagnol["element_93"] = ""; // TRADUCTION MANQUANTE
espagnol["element_94"] = ""; // TRADUCTION MANQUANTE
espagnol["element_95"] = ""; // TRADUCTION MANQUANTE
espagnol["element_96"] = ""; // TRADUCTION EN ATTENTE
espagnol["element_97"] = ""; // TRADUCTION EN ATTENTE
espagnol["element_98"] = ""; // TRADUCTION EN ATTENTE
espagnol["element_99"] = ""; // TRADUCTION EN ATTENTE
espagnol["element_100"] = ""; // TRADUCTION EN ATTENTE
espagnol["element_101"] = ""; // TRADUCTION EN ATTENTE
