var italien = {};
italien["lang"] = "it";
italien["element_1"] = " / Denuncia per furto"; //ANCIENNE TRAD
italien["element_2"] = " / Tipo di furto";
italien["element_3"] = " / borseggio (oggetti rubati su una persona, nelle tasche, o nella borsa che teneva)";
italien["element_4"] = " / furto (oggetti rubati per terra o su una tavola...)";
italien["element_5"] = " / dove si trovava l’oggetto";
italien["element_6"] = " / Data dei fatti";
italien["element_7"] = " / Ora dei fatti";
italien["element_8"] = " / Luogo"; //ANCIENNE TRAD
italien["element_9"] = " / Identità della vittima";
italien["element_10"] = " / Cognome"; // TRADUCTION EN ATTENTE
italien["element_11"] = " / Nome";
italien["element_12"] = " / Data di nascita";
italien["element_13"] = " / Luogo di nascita";
italien["element_14"] = " / Cittadinanza";
italien["element_15"] = " / Professione";
italien["element_16"] = " / Dettagli della vittima";
italien["element_17"] = " / Indirizzo";
italien["element_18"] = " / Numero di telefono";
italien["element_19"] = " / e-mail";
italien["element_20"] = " / Indirizzo a Parigi";
italien["element_21"] = " / Durata del soggiorno"; //ANCIENNE TRAD
italien["element_22"] = " / degli autori";
italien["element_22_bis"] = " / degli autori";
italien["element_23"] = " / Non sono in grado di riconoscere l’autore (gli autori) del furto, tuttavia posso chiarire gli elementi seguenti riguardandoli"; // TRADUCTION EN ATTENTE
italien["element_24"] = " / Quante persone";
italien["element_25"] = " / Sesso";
italien["element_26"] = " / uomo";
italien["element_27"] = " / donna";
italien["element_28"] = " / Età";
italien["element_29"] = " / Altezza (cm)";
italien["element_30"] = " / Corpulenza";
italien["element_31"] = " / grasso";
italien["element_32"] = " / normale";
italien["element_33"] = " / magro";
italien["element_34"] = " / Tipo"; // VERIFIER TRADUCTION
italien["element_40"] = " / altro";
italien["element_41"] = " / colore dei capelli";
italien["element_42"] = " / neri";
italien["element_43"] = " / castani";
italien["element_44"] = " / biondi";
italien["element_45"] = " / bianchi";
italien["element_46"] = " / rossi/fulvi";
italien["element_47"] = " / calvo";
italien["element_49"] = " / segni particolari";
italien["element_50"] = " / baffi";
italien["element_51"] = " / barba";
italien["element_52"] = " / occhiali";
italien["element_53"] = " / cicatrice";
italien["element_54"] = " / tatuaggio";
italien["element_55"] = " / piercing";
// Duplication
italien["element_25_bis"] = " / Sesso";
italien["element_26_bis"] = " / uomo";
italien["element_27_bis"] = " / donna";
italien["element_28_bis"] = " / Età";
italien["element_29_bis"] = " / Altezza (cm)";
italien["element_30_bis"] = " / Corpulenza";
italien["element_31_bis"] = " / grasso";
italien["element_32_bis"] = " / normale";
italien["element_33_bis"] = " / magro";
italien["element_34_bis"] = " / Tipo"; // VERIFIER TRADUCTION
italien["element_40_bis"] = " / altro";
italien["element_41_bis"] = " / colore dei capelli";
italien["element_42_bis"] = " / neri";
italien["element_43_bis"] = " / castani";
italien["element_44_bis"] = " / biondi";
italien["element_45_bis"] = " / bianchi";
italien["element_46_bis"] = " / rossi/fulvi";
italien["element_47_bis"] = " / calvo";
italien["element_49_bis"] = " / segni particolari";
italien["element_50_bis"] = " / baffi";
italien["element_51_bis"] = " / barba";
italien["element_52_bis"] = " / occhiali";
italien["element_53_bis"] = " / cicatrice";
italien["element_54_bis"] = " / tatuaggio";
italien["element_55_bis"] = " / piercing";
// Fin Duplication
italien["element_56"] = " / Pregiusizio";
italien["element_57"] = " / oggetti rubati/derubati";
italien["element_58"] = " / indicare tutti i dettagli necessari (numero di serie oppure IMEI)";
italien["element_59"] = " / borsa/borsetta, portafoglio o portamonete";
italien["element_60"] = " / contanti";
italien["element_61"] = " / carta di credito";
italien["element_62"] = " / travellers check";
italien["element_63"] = " / biglietto d’aereo";
italien["element_64"] = " / passaporto";
italien["element_65"] = " / carta d’identità";
italien["element_66"] = " / patente";
italien["element_67"] = " / elefonino/cellulare";
italien["element_68"] = " / macchina fotografica";
italien["element_69"] = " / videocamera";
italien["element_70"] = " / gioielli";
italien["element_71"] = " / altri oggetti";
italien["element_72"] = " / aggiungere";
italien["element_73"] = " / modus operandi";
italien["element_74"] = " / Descrivere in che modo pensa che si sia svolto il furto";
italien["element_75"] = " / Firma del denunciante";
italien["element_76"] = " / Dichiaro sporgere denuncia a carico di ignoti per i fatti relatati, presso il Procuratore della Repubblica del Tribunal de Grande Instance di Parigi";
italien["element_77"] = " / precedente";
italien["element_78"] = " / seguente";
italien["element_79"] = "";
italien["element_80"] = " / rimuovere";
italien["element_81"] = " / reset";
italien["element_82"] = " / Individuo 1";
italien["element_83"] = " / Individuo 2";
italien["element_84"] = "";
italien["element_85"] = "";
italien["element_86"] = "";
italien["element_87"] = "";
italien["element_88"] = "";
italien["element_89"] = "";
italien["element_90"] = "";
italien["element_91"] = "";
italien["element_92"] = ""; // TRADUCTION MANQUANTE
italien["element_93"] = ""; // TRADUCTION MANQUANTE
italien["element_94"] = ""; // TRADUCTION MANQUANTE
italien["element_95"] = ""; // TRADUCTION MANQUANTE
italien["element_96"] = ""; // TRADUCTION EN ATTENTE
italien["element_97"] = ""; // TRADUCTION EN ATTENTE
italien["element_98"] = ""; // TRADUCTION EN ATTENTE
italien["element_99"] = ""; // TRADUCTION EN ATTENTE
italien["element_100"] = ""; // TRADUCTION EN ATTENTE
italien["element_101"] = ""; // TRADUCTION EN ATTENTE
