var japonais = {};
japonais["lang"] = "ja";
japonais["element_1"] = " / 盗難被害届"; //ANCIENNE TRAD
japonais["element_2"] = " / 盗難の種類";
japonais["element_3"] = " / すり・ひったくり";
japonais["element_4"] = " / <br>置き引き";
japonais["element_5"] = " / 盗難状況";
japonais["element_6"] = " / 犯罪の日";
japonais["element_7"] = " / 犯罪の時間";
japonais["element_8"] = " / 事件発生場所"; //ANCIENNE TRAD
japonais["element_9"] = " / 犠牲者";
japonais["element_10"] = " / 姓"; // TRADUCTION EN ATTENTE
japonais["element_11"] = " / 名";
japonais["element_12"] = " / 生年月日（西暦）";
japonais["element_13"] = " / 出生地（都道府県名 )";
japonais["element_14"] = " / 国籍";
japonais["element_15"] = " / 職業";
japonais["element_16"] = " / 被害者の連絡先情報";
japonais["element_17"] = " / 居住地の住所";
japonais["element_18"] = " / 電話番号";
japonais["element_19"] = " / 電子メイル";
japonais["element_20"] = " / パリ市内の滞在先住所";
japonais["element_21"] = " / 滞在期間"; //ANCIENNE TRAD
japonais["element_22"] = " / 加害者の説明";
japonais["element_22_bis"] = " / 加害者の説明";
japonais["element_23"] = " / 犯人を特定することはできませんが、気がついたことを下記のとおりお知らせいたします。"; // TRADUCTION EN ATTENTE
japonais["element_24"] = " / 人数";
japonais["element_25"] = " / 性別";
japonais["element_26"] = " / 男性";
japonais["element_27"] = " / 女性";
japonais["element_28"] = " / 年齢";
japonais["element_29"] = " / 身長 (cms)";
japonais["element_30"] = " / 肥満";
japonais["element_31"] = " / 太め";
japonais["element_32"] = " / 普通";
japonais["element_33"] = " / 痩せ型";
japonais["element_34"] = " / 見た目"; // VERIFIER TRADUCTION
japonais["element_40"] = " / その他";
japonais["element_41"] = " / 髪の色";
japonais["element_42"] = " / 黒";
japonais["element_43"] = " / 茶";
japonais["element_44"] = " / 金髪";
japonais["element_45"] = " / 白髪";
japonais["element_46"] = " / 赤毛";
japonais["element_47"] = " / はげ";
japonais["element_49"] = " / 特徴";
japonais["element_50"] = " / 口ひげ";
japonais["element_51"] = " / あごひげ";
japonais["element_52"] = " / 眼鏡";
japonais["element_53"] = " / 傷跡";
japonais["element_54"] = " / 入れ墨";
japonais["element_55"] = " / ピアス";
// Duplication
japonais["element_25_bis"] = " / 性別";
japonais["element_26_bis"] = " / 男性";
japonais["element_27_bis"] = " / 女性";
japonais["element_28_bis"] = " / 年齢";
japonais["element_29_bis"] = " / 身長 (cms)";
japonais["element_30_bis"] = " / 肥満";
japonais["element_31_bis"] = " / 太め";
japonais["element_32_bis"] = " / 普通";
japonais["element_33_bis"] = " / 痩せ型";
japonais["element_34_bis"] = " / 見た目"; // VERIFIER TRADUCTION
japonais["element_40_bis"] = " / その他";
japonais["element_41_bis"] = " / 髪の色";
japonais["element_42_bis"] = " / 黒";
japonais["element_43_bis"] = " / 茶";
japonais["element_44_bis"] = " / 金髪";
japonais["element_45_bis"] = " / 白髪";
japonais["element_46_bis"] = " / 赤毛";
japonais["element_47_bis"] = " / はげ";
japonais["element_49_bis"] = " / 特徴";
japonais["element_50_bis"] = " / 口ひげ";
japonais["element_51_bis"] = " / あごひげ";
japonais["element_52_bis"] = " / 眼鏡";
japonais["element_53_bis"] = " / 傷跡";
japonais["element_54_bis"] = " / 入れ墨";
japonais["element_55_bis"] = " / ピアス";
// Fin Duplication
japonais["element_56"] = " / 被害";
japonais["element_57"] = " / 盗難品";
japonais["element_58"] = " / 詳細に記載 (可能な限り端末識別番号（IMEI）";
japonais["element_59"] = " / ハンドバッ グ、財布又は小銭入れに関す";
japonais["element_60"] = " / 現金";
japonais["element_61"] = " / クレジットカード";
japonais["element_62"] = " / トラベラーズチェック";
japonais["element_63"] = " / 航空券";
japonais["element_64"] = " / パスポート";
japonais["element_65"] = " / 身分証明書";
japonais["element_66"] = " / 運転免許証";
japonais["element_67"] = " / 携帯電話";
japonais["element_68"] = " / カメラ";
japonais["element_69"] = " / ビデオカメラ ";
japonais["element_70"] = " / 宝石類";
japonais["element_71"] = " / その他の物";
japonais["element_72"] = " / 追加";
japonais["element_73"] = " / 犯罪の手口について";
japonais["element_74"] = " / 盗難はどのような手口で行われたと思いますか（詳細に記載して下さい）。";
japonais["element_75"] = " / 告訴人の署名";
japonais["element_76"] = " / 私は、上記の事件について氏名不詳の被疑者に対する被害届をパリ大審裁判所検事正に 提出いたし ます。";
japonais["element_77"] = " / 前";
japonais["element_78"] = " / 以下";
japonais["element_79"] = "";
japonais["element_80"] = " / 取り除きます";
japonais["element_81"] = " / リセット";
japonais["element_82"] = " / １人目";
japonais["element_83"] = " / ２人目";
japonais["element_84"] = "";
japonais["element_85"] = "";
japonais["element_86"] = "";
japonais["element_87"] = "";
japonais["element_88"] = "";
japonais["element_89"] = "";
japonais["element_90"] = "";
japonais["element_91"] = "";
japonais["element_92"] = ""; // TRADUCTION MANQUANTE
japonais["element_93"] = ""; // TRADUCTION MANQUANTE
japonais["element_94"] = ""; // TRADUCTION MANQUANTE
japonais["element_95"] = ""; // TRADUCTION MANQUANTE
japonais["element_96"] = ""; // TRADUCTION EN ATTENTE
japonais["element_97"] = ""; // TRADUCTION EN ATTENTE
japonais["element_98"] = ""; // TRADUCTION EN ATTENTE
japonais["element_99"] = ""; // TRADUCTION EN ATTENTE
japonais["element_100"] = ""; // TRADUCTION EN ATTENTE
japonais["element_101"] = ""; // TRADUCTION EN ATTENTE
