var russe = {};
russe["lang"] = "ru";
russe["element_1"] = " / Заявление о краже"; //ANCIENNE TRAD
russe["element_2"] = " / тип краже";
russe["element_3"] = " / карманная кража (кража вещей находившихся при потерпевшем,  из его карманов или ручной клади)";
russe["element_4"] = " / простая кража (кража вещей находившихся на расстоянии от потерпевшего - на земле, на столе…)";
russe["element_5"] = " / уточните где находились украденные вещи";
russe["element_6"] = " / дата совершения преступления";
russe["element_7"] = " / время совершения преступления";
russe["element_8"] = " / место совершения преступления"; //ANCIENNE TRAD
russe["element_9"] = " / Идентичность жертвы";
russe["element_10"] = " / фамилия"; // TRADUCTION EN ATTENTE
russe["element_11"] = " / имя";
russe["element_12"] = " / дата рождения";
russe["element_13"] = " / место рождения";
russe["element_14"] = " / гражданство";
russe["element_15"] = " / профессия";
russe["element_16"] = " / Детали жертвы";
russe["element_17"] = " / адрес";
russe["element_18"] = " / номер телефона";
russe["element_19"] = " / E-mail";
russe["element_20"] = " / адрес в Париже";
russe["element_21"] = " / срок пребывания"; //ANCIENNE TRAD
russe["element_22"] = " / описание лица совершившего кражу";
russe["element_23"] = " / Я не могу опознать лицо совершившее кражу но я могу уточнить следующее"; // TRADUCTION EN ATTENTE
russe["element_24"] = " / Количество лиц совершивших кражу";
russe["element_25"] = " / пол";
russe["element_26"] = " / мужчина";
russe["element_27"] = " / женщина";
russe["element_28"] = " / возраст";
russe["element_29"] = " / рост";
russe["element_30"] = " / тучность";
russe["element_31"] = " / полный";
russe["element_32"] = " / средний";
russe["element_33"] = " / худой";
russe["element_34"] = " / внешность"; // VERIFIER TRADUCTION
russe["element_40"] = " / другая";
russe["element_41"] = " / цвет волос";
russe["element_42"] = " / черный";
russe["element_43"] = " / каштанновый";
russe["element_44"] = " / русый";
russe["element_45"] = " / седой";
russe["element_46"] = " / рыжый";
russe["element_47"] = " / лысый";
russe["element_49"] = " / особенности";
russe["element_50"] = " / усы";
russe["element_51"] = " / борода";
russe["element_52"] = " / очки";
russe["element_53"] = " / шрам";
russe["element_54"] = " / татуаж";
russe["element_55"] = " / пирсинг";
// Duplication pour l'individu 2
russe["element_22_bis"] = " / описание лица совершившего кражу";
russe["element_23_bis"] = " / Я не могу опознать лицо совершившее кражу но я могу уточнить следующее";
russe["element_24_bis"] = " / Количество лиц совершивших кражу";
russe["element_25_bis"] = " / пол";
russe["element_26_bis"] = " / мужчина";
russe["element_27_bis"] = " / женщина";
russe["element_28_bis"] = " / возраст";
russe["element_29_bis"] = " / рост";
russe["element_30_bis"] = " / тучность";
russe["element_31_bis"] = " / полный";
russe["element_32_bis"] = " / средний";
russe["element_33_bis"] = " / худой";
russe["element_34_bis"] = " / внешность"; // VERIFIER TRADUCTION
russe["element_40_bis"] = " / другая";
russe["element_41_bis"] = " / цвет волос";
russe["element_42_bis"] = " / черный";
russe["element_43_bis"] = " / каштанновый";
russe["element_44_bis"] = " / русый";
russe["element_45_bis"] = " / седой";
russe["element_46_bis"] = " / рыжый";
russe["element_47_bis"] = " / лысый";
russe["element_49_bis"] = " / особенности";
russe["element_50_bis"] = " / усы";
russe["element_51_bis"] = " / борода";
russe["element_52_bis"] = " / очки";
russe["element_53_bis"] = " / шрам";
russe["element_54_bis"] = " / татуаж";
russe["element_55_bis"] = " / пирсинг";
// Fin Duplication pour l'individu 2
russe["element_56"] = " / УЩЕРБ";
russe["element_57"] = " / украденные вещи";
russe["element_58"] = " / уточните все необходимые детали";
russe["element_59"] = " / сумочка, бумажник или кошелёк";
russe["element_60"] = " / наличные деньги";
russe["element_61"] = " / кредитная карточка";
russe["element_62"] = " / дорожные чеки";
russe["element_63"] = " / авиабилет";
russe["element_64"] = " / паспорт";
russe["element_65"] = " / документ, удостоверяющий личность";
russe["element_66"] = " / водительские права";
russe["element_67"] = " / мобильный телефон";
russe["element_68"] = " / фотоаппарат";
russe["element_69"] = " / кинокамера";
russe["element_70"] = " / украшения";
russe["element_71"] = " / другое";
russe["element_72"] = " / Добавить пункт";
russe["element_73"] = " / порядок действий";
russe["element_74"] = " / Опишите обстоятельства при которых, по вашему мнению, произошла кража";
russe["element_75"] = " / Подпись заявителя";
russe["element_76"] = " / Я имею честь подать жалобу на имя Прокурора Суда Большой Инстанции Парижа на неизвестного совершившего вышеуказанную кражу";
russe["element_77"] = " / предыдущий";
russe["element_78"] = " / следующий";
russe["element_79"] = "";
russe["element_80"] = " / Удалить объект";
russe["element_81"] = " / сброс";
russe["element_82"] = " / 1 лицо";
russe["element_83"] = " / 2 лицо";
russe["element_84"] = "";
russe["element_85"] = "";
russe["element_86"] = "";
russe["element_87"] = "";
russe["element_88"] = "";
russe["element_89"] = "";
russe["element_90"] = "";
russe["element_91"] = "";
russe["element_92"] = ""; // TRADUCTION MANQUANTE
russe["element_93"] = ""; // TRADUCTION MANQUANTE
russe["element_94"] = ""; // TRADUCTION MANQUANTE
russe["element_95"] = ""; // TRADUCTION MANQUANTE
russe["element_96"] = ""; // TRADUCTION EN ATTENTE
russe["element_97"] = ""; // TRADUCTION EN ATTENTE
russe["element_98"] = ""; // TRADUCTION EN ATTENTE
russe["element_99"] = ""; // TRADUCTION EN ATTENTE
russe["element_100"] = ""; // TRADUCTION EN ATTENTE
russe["element_101"] = ""; // TRADUCTION EN ATTENTE
