var turc = {};
turc["lang"] = "tr";
turc["element_1"] = " / HIRSIZLIK ṢiKAYET FORMU"; //ANCIENNE TRAD
turc["element_2"] = " / Hırsızlık türü";
turc["element_3"] = " / yankesicilik (mağdur olan kişinin çalınan eşyaları cepte veya el cantasında olması)";
turc["element_4"] = " / normal hırsızlık ( mağdur olan kişinin çalınan eşyaları yerde veya masa üstünde olması) ( arka arkaya dönuk hırsızlık)";
turc["element_5"] = " / Çalınan eşyaların yeri";
turc["element_6"] = " / Suç tarihi";
turc["element_7"] = " / Suç saatleri";
turc["element_8"] = " / OLAY YERi"; //ANCIENNE TRAD
turc["element_9"] = " / Mağdur kişisel bilgiler";
turc["element_10"] = " / soyadı"; // TRADUCTION EN ATTENTE
turc["element_11"] = " / adı";
turc["element_12"] = " / doğum tarihi";
turc["element_13"] = " / doğum yeri";
turc["element_14"] = " / Uyruğu";
turc["element_15"] = " / mesleği";
turc["element_16"] = " / Mağdur iletişim bilgileri";
turc["element_17"] = " / adres";
turc["element_18"] = " / telefon numarası";
turc["element_19"] = " / E-mail";
turc["element_20"] = " / Paris adresi";
turc["element_21"] = " / seyahat süreci"; //ANCIENNE TRAD
turc["element_22"] = " / Hirsizlarin Tanimi";
turc["element_22_bis"] = " / Hirsizlarin Tanimi";
turc["element_23"] = " / Zanlıları hatırlıyamıyorum ama sizlere bazı detayları veriyorum"; // TRADUCTION EN ATTENTE
turc["element_24"] = " / Zanlıların sayısı";
turc["element_25"] = " / cinsiyeti";
turc["element_26"] = " / erkek";
turc["element_27"] = " / bayan";
turc["element_28"] = " / yaṣ";
turc["element_29"] = " / boy (cm)";
turc["element_30"] = " / şişmanlık";
turc["element_31"] = " / ṣiṣman";
turc["element_32"] = " / normal";
turc["element_33"] = " / zayıf";
turc["element_34"] = " / uyruk tipi"; // VERIFIER TRADUCTION
turc["element_40"] = " / diḡer";
turc["element_41"] = " / saç rengi";
turc["element_42"] = " / siyah";
turc["element_43"] = " / kahverengi";
turc["element_44"] = " / sarı";
turc["element_45"] = " / beyaz";
turc["element_46"] = " / kızıl";
turc["element_47"] = " / Kel";
turc["element_49"] = " / özellikler";
turc["element_50"] = " / bıyıklı";
turc["element_51"] = " / sakallı";
turc["element_52"] = " / gözlüklü";
turc["element_53"] = " / yara izi";
turc["element_54"] = " / dövme";
turc["element_55"] = " / persing";
// Duplication
turc["element_25_bis"] = " / cinsiyeti";
turc["element_26_bis"] = " / erkek";
turc["element_27_bis"] = " / bayan";
turc["element_28_bis"] = " / yaṣ";
turc["element_29_bis"] = " / boy (cm)";
turc["element_30_bis"] = " / şişmanlık";
turc["element_31_bis"] = " / ṣiṣman";
turc["element_32_bis"] = " / normal";
turc["element_33_bis"] = " / zayıf";
turc["element_34_bis"] = " / uyruk tipi"; // VERIFIER TRADUCTION
turc["element_40_bis"] = " / diḡer";
turc["element_41_bis"] = " / saç rengi";
turc["element_42_bis"] = " / siyah";
turc["element_43_bis"] = " / kahverengi";
turc["element_44_bis"] = " / sarı";
turc["element_45_bis"] = " / beyaz";
turc["element_46_bis"] = " / kızıl";
turc["element_47_bis"] = " / Kel";
turc["element_49_bis"] = " / özellikler";
turc["element_50_bis"] = " / bıyıklı";
turc["element_51_bis"] = " / sakallı";
turc["element_52_bis"] = " / gözlüklü";
turc["element_53_bis"] = " / yara izi";
turc["element_54_bis"] = " / dövme";
turc["element_55_bis"] = " / persing";
// Fin Duplication
turc["element_56"] = " / HASAR";
turc["element_57"] = " / çalınan eṣyalar";
turc["element_58"] = " / detaylı şekilde belirleyiniz, Cep telefonuzun IMEI (seri numarasını belirleyiniz)";
turc["element_59"] = " / el çantası,cüzdan, bozuk para cüzdanı";
turc["element_60"] = " / nakit para";
turc["element_61"] = " / Kredi karti";
turc["element_62"] = " / seyahat çeki";
turc["element_63"] = " / uçak bileti";
turc["element_64"] = " / Pasaport";
turc["element_65"] = " / Kimlik karti";
turc["element_66"] = " / sürücü Belgesi";
turc["element_67"] = " / cep telefonu";
turc["element_68"] = " / Fotoraf  makinesi";
turc["element_69"] = " / video kamera";
turc["element_70"] = " / Takı";
turc["element_71"] = " / Diḡer eșya";
turc["element_72"] = " / eklemek";
turc["element_73"] = " / olayın ṣekli";
turc["element_74"] = " / hırsızlık olayın nasıl geçtiğini belirtir misiniz";
turc["element_75"] = " / Mağdurun imzası";
turc["element_76"] = " / Mağdur olduğum hırsızlık olayında zanlıların bulunmadıǧından dolayı , Paris hukuk mahkemesi savcısına şikayette bulunuyorum";
turc["element_77"] = " / önceki";
turc["element_78"] = " / aşağıdaki";
turc["element_79"] = "";
turc["element_80"] = " / kaldırmak";
turc["element_81"] = " / sıfırlamak";
turc["element_82"] = " / birinci Zanlı";
turc["element_83"] = " / ikinci Zanlı";
turc["element_84"] = "";
turc["element_85"] = "";
turc["element_86"] = "";
turc["element_87"] = "";
turc["element_88"] = "";
turc["element_89"] = "";
turc["element_90"] = "";
turc["element_91"] = "";
turc["element_92"] = ""; // TRADUCTION MANQUANTE
turc["element_93"] = ""; // TRADUCTION MANQUANTE
turc["element_94"] = ""; // TRADUCTION MANQUANTE
turc["element_95"] = ""; // TRADUCTION MANQUANTE
turc["element_96"] = ""; // TRADUCTION EN ATTENTE
turc["element_97"] = ""; // TRADUCTION EN ATTENTE
turc["element_98"] = ""; // TRADUCTION EN ATTENTE
turc["element_99"] = ""; // TRADUCTION EN ATTENTE
turc["element_100"] = ""; // TRADUCTION EN ATTENTE
turc["element_101"] = ""; // TRADUCTION EN ATTENTE
